import localFont from "next/font/local";
import Header from "./components/header";
import 'bootstrap/dist/css/bootstrap.min.css';
import './public/sass/helper/base.scss';
import './public/sass/helper/helper.scss';
import './public/sass/helper/reset.scss';
import './public/sass/global.scss';
import { Inter } from 'next/font/google';
import 'animate.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Footer from "./components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
